---
- name: install EPEL repository
  yum_repository:
    name: epel
    state: present
    description: EPEL YUM repo
    baseurl: "{{ epel_repo_url }}"
    gpgkey: "{{ epel_gpg_url }}"
    gpgcheck: "{{ epel_gpg_check }}"
  notify:
    - update cache