---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
  options:
    config-file: yamllint-config.yaml
platforms:
  - name: centos
    instance_name: epel-vm
    box: centos/7
    provider_name: virtualbox
    provider_memory: 512
    provider_cpus: 1
provisioner:
  name: ansible
  playbooks:
    converge: playbook.yml
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  directory: ../../tests
  lint:
    name: flake8